### PR TITLE
Update to use new libp2p-swarm, peer-id, pull-stream, etc

### PR DESCRIPTION
**Pull request by yusefnapora**
This updates the router and test code to be compatible with libp2p-swarm 0.26.4 and the new async peer-id and peer-info apis.  Also uses pull-stream with the protocol-buffers module to deal with the protobufs and connections.

I didn't update the compliance test, but things pass now if you run `npm run test` 😄 I think the `abstract-peer-routing` test needs to be updated before the compliance tests can be, since it's calling `Id.create()` synchronously still.

### CODE REVIEW

**Comment by yusefnapora** [comment]
hmm, things seem to be failing pretty hard on Travis; I get the same on node 4 locally:

```
/Users/yusef/Work/Code/js-libp2p-kad-routing/node_modules/libp2p-crypto/src/crypto/util.js:18
  return new BN(Buffer.from(str, 'base64'))
                       ^

TypeError: base64 is not a function
    at Function.from (native)
    at Function.from (native)
    at toBn (/Users/yusef/Work/Code/js-libp2p-kad-routing/node_modules/libp2p-crypto/src/crypto/util.js:18:24)
    at Object.exports.jwkToPkix (/Users/yusef/Work/Code/js-libp2p-kad-routing/node_modules/libp2p-crypto/src/crypto/rsa-utils.js:109:18)
    at RsaPublicKey.marshal (/Users/yusef/Work/Code/js-libp2p-kad-routing/node_modules/libp2p-crypto/src/keys/rsa.js:20:25)
    at RsaPublicKey.bytes (/Users/yusef/Work/Code/js-libp2p-kad-routing/node_modules/libp2p-crypto/src/keys/rsa.js:26:18)
    at RsaPublicKey.hash (/Users/yusef/Work/Code/js-libp2p-kad-routing/node_modules/libp2p-crypto/src/keys/rsa.js:40:22)
    at /Users/yusef/Work/Code/js-libp2p-kad-routing/node_modules/peer-id/src/index.js:98:37
    at nextTask (/Users/yusef/Work/Code/js-libp2p-kad-routing/node_modules/async/waterfall.js:28:14)
    at /Users/yusef/Work/Code/js-libp2p-kad-routing/node_modules/async/waterfall.js:22:13
    at apply (/Users/yusef/Work/Code/js-libp2p-kad-routing/node_modules/lodash/_apply.js:15:25)
    at /Users/yusef/Work/Code/js-libp2p-kad-routing/node_modules/lodash/_overRest.js:32:12
    at /Users/yusef/Work/Code/js-libp2p-kad-routing/node_modules/async/internal/onlyOnce.js:12:16
    at /Users/yusef/Work/Code/js-libp2p-kad-routing/node_modules/libp2p-crypto/src/keys/rsa.js:117:5
    at /Users/yusef/Work/Code/js-libp2p-kad-routing/node_modules/nodeify/index.js:15:9
    at doNTCallback0 (node.js:407:9)
    at process._tickDomainCallback (node.js:377:13)
```

**Comment by yusefnapora** [comment]
Ah, it seems that `Buffer.from` [only exists in node 5.11.1 or later](http://stackoverflow.com/a/14573049).  I guess  js-libp2p-crypto could check whether `Buffer.from` exists and fall back to `new Buffer(contents, 'base64')`, assuming you still want to support node 4.

**Comment by yusefnapora** [comment]
Green at last! Only for node 5+ though (tested with 5.12.0 and 6.9.1).  It seems libp2p-crypto has problems with node 4 even if you work around the Buffer.from issue; I got a bunch of errors complaining that things weren't `TypedArray`s when I tried earlier.

**Comment by dignifiedquire** [comment]
@yusefnapora thanks for noticing, not sure how this slipped as the tests should be running on Node4. Could you open an issue on the libp2p-crypto repo with your findings please?

**Comment by yusefnapora** [comment]
@dignifiedquire sure, will do; I just realized that it looks like a minor version thing; this repo was set to use node `4.0` in .travis.yml, but libp2p-crypto just says to use `4`, which grabs the most recent 4.x version that `nvm` knows about.  

I just installed 4.7.0 locally, and the js-libp2p-crypto and kad routing tests all pass.  So maybe just making the "engines" dependency a little stricter would be the simplest thing to do?  I'll try a few other minor versions to see which is the actual minimum 4.x that passes and open an issue over there after.

**Comment by daviddias** [comment]
@yusefnapora thank you! I haven't updated this module in a while as the focus has been in other parts of libp2p and js-ipfs, I can't vet that this module current structure will be the one integrated in libp2p, but it can definitely be used for experimentation.

**Pull request merged**
